-- ============================================================================
-- Flyway V3.1 Create Complainant Related Information Master Reporting Table
-- ============================================================================

CREATE TABLE IF NOT EXISTS `complainant_related_information` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `unique_id_no` VARCHAR(100) NOT NULL UNIQUE,
    `date_of_complaint` DATETIME NULL,
    `name_of_complainant` VARCHAR(255) NULL,
    `account_no` VARCHAR(50) NULL,
    `contact_address` VARCHAR(255) NULL,
    `customer_segment` VARCHAR(100) NULL,
    `received_by` VARCHAR(100) NULL,
    `complaint_made_on_channel` VARCHAR(100) NULL,
    `specific_channel_name` VARCHAR(100) NULL,
    `district_department` VARCHAR(100) NULL,
    `service_type` VARCHAR(100) NULL,
    `details_of_complaint` TEXT NULL,
    `complaint_classification` VARCHAR(100) NULL,
    `supporting_evidence` VARCHAR(255) NULL,
    `complainant_acknowledged` VARCHAR(50) NULL DEFAULT '-',
    `complaint_justified` VARCHAR(50) NULL DEFAULT '-',
    `validity_reason_for_justified_complaints` TEXT NULL,
    `nature_of_complaints` VARCHAR(255) NULL,
    `complaints_category` VARCHAR(100) NULL,
    `case_assigned_to` VARCHAR(100) NULL,
    `expected_resolution_date` DATETIME NULL,
    `actual_resolution_date` DATETIME NULL,
    `resolution_time_working_days` INT NULL DEFAULT 0,
    `case_forwarded_to` VARCHAR(100) NULL,
    `date_case_forwarded` DATETIME NULL,
    `reason_for_forwarding` TEXT NULL,
    `case_status` VARCHAR(50) NOT NULL DEFAULT 'RECORDED',
    `escalated_to` VARCHAR(100) NULL,
    `date_of_escalation` DATETIME NULL,
    `reason_for_escalation` TEXT NULL,
    `resolution_plan` TEXT NULL,
    `resolution_outcome_notified` VARCHAR(50) NULL DEFAULT '-',
    `means_of_notification` VARCHAR(100) NULL,
    `complainant_acknowledged_resolution` VARCHAR(50) NULL DEFAULT '-',
    `advice_given_to_complainant` TEXT NULL,
    `customer_reaction_to_handling_process` VARCHAR(100) NULL,
    `customer_lifetime_value` VARCHAR(100) NULL DEFAULT '-',
    `remark_and_special_note` TEXT NULL,
    `requires_follow_up` VARCHAR(50) NULL DEFAULT '-',
    `latest_status_and_remark` TEXT NULL,
    `is_manually_edited` BOOLEAN NOT NULL DEFAULT FALSE,
    `last_edited_by` VARCHAR(100) NULL,
    `last_edited_at` DATETIME NULL,
    `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_cri_unique_id_no` (`unique_id_no`),
    INDEX `idx_cri_case_status` (`case_status`),
    INDEX `idx_cri_complaints_category` (`complaints_category`),
    INDEX `idx_cri_date_of_complaint` (`date_of_complaint`),
    INDEX `idx_cri_district_department` (`district_department`),
    INDEX `idx_cri_case_assigned_to` (`case_assigned_to`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;