-- Consolidate ROLE_CONTACT_CENTER_MANAGER into ROLE_CONTACT_CENTER_SENIOR_MANAGER.
UPDATE users
SET role = 'ROLE_CONTACT_CENTER_SENIOR_MANAGER'
WHERE role IN (
        'ROLE_CONTACT_CENTER_MANAGER',
        'CONTACT_CENTER_MANAGER',
        'Contact Center Manager'
    )
    OR REPLACE(UPPER(TRIM(role)), ' ', '_') IN (
        'ROLE_CONTACT_CENTER_MANAGER',
        'CONTACT_CENTER_MANAGER'
    );
