package com.dashenbank.cms.model;

public enum Role {
    ROLE_CONTACT_CENTER_AGENT,
    ROLE_DIGITAL_MARKETING_OFFICER,
    ROLE_DEPARTMENT_WORKUNIT,
    ROLE_CHIEF_COMMITTEE,
    ROLE_ADMIN,

    // Customer Care Division Roles
    ROLE_CUSTOMER_CARE_SENIOR_MANAGER,
    ROLE_CUSTOMER_CARE_TEAM_LEADER,
    ROLE_CUSTOMER_CARE_OFFICER,
    ROLE_SERVICE_QUALITY_DIRECTOR,

    // Executive Monitoring Roles
    ROLE_CHIEF_EXPERIENCE_OFFICER,

    // Operational Management Roles
    ROLE_BRANCH_MANAGER,
    ROLE_CONTACT_CENTER_SENIOR_MANAGER,
    ROLE_DIGITAL_MARKETING_SENIOR_MANAGER,
    ROLE_CUSTOMER_EXPERIENCE_PARTNERSHIP,
    ROLE_CUSTOMER_SERVICE_MANAGER,

    // Audit Roles
    ROLE_AUDIT_INVESTIGATION_TEAM,
    ROLE_OPERATIONAL_AUDIT_SENIOR_MANAGER,
    ROLE_OPERATIONAL_AUDIT_DIRECTOR,

    // Committee Role
    ROLE_COMMITTEE_SECRETARY
}
