package com.dashenbank.cms.model;

public enum SecurityAuditEvent {
    SUCCESSFUL_LOGIN,
    FAILED_LOGIN,
    LOGOUT,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    PASSWORD_CHANGED,
    PASSWORD_EXPIRED,
    PASSWORD_RESET,
    SESSION_TIMEOUT,
    COMPLAINT_CREATED,
    TASK_CLAIMED,
    TASK_COMPLETED,
    ROLE_CHANGED,
    LDAP_SYNC,
    NOTIFICATION_SENT
}
